### ISSUE TITLE
Service/Client issue with ROS2 Jazzy

### ISSUE THREAD

**Issue by nisseknudsen** [jhelovuo/ros2-client#35]
Hi there,
thank you for providing this awesome library! 

I've been successfuly in communicating with ROS pubs and subs via `ros2_client` in Rust, that's been a good experience.

Now I am looking into connecting Client/Service, and ran into some issues.

I am able to setup a Server in `ros2_client` and successfully receive a request message from my ros2 jazzy client when using `ServiceMapping::Enhanced`.
Unfortunately, my  ros2 client never receives the response (it just spins as if nothing was coming its way).
I tested also `ServiceMapping::Basic`, but then the client request fails in a `ros2_client` unwrap call with some headers.
When setting to `ServiceMapping::Cyclone`, I can receive from the client, and when sending a response back, I do some ros logs about error in changing byte sizes (so something _must_ have reached it).

When using a ros2 service with a `ros2_client` Client, the ros2 service never receives my initial request. I tried different `ServiceMapping`s, but no success.

So in summary, it seems that sending requests/replies _to_ a ros2 endpoint does not work for me.

What do I have to do to make it work with ros2 jazzy (should be using fastdds).
My test applications are the minimal client and service examples from the official ros2 repo.

```
let proxy_ros_client = node.create_client::<RosService>(
        ServiceMapping::Enhanced,
        &Name::new("/", "add_two_ints")?,
        &ServiceTypeName::new("example_interfaces", "AddTwoInts"),
        QosPolicies::default(),
        QosPolicies::default(),
    )?;

 let req_id = proxy_ros_client.async_send_request(example_interfaces::AddTwoIntsReq { a: 1, b: 2 }).await?; // <-- executes promptly and getting a request id back
let res = proxy_ros_client.async_receive_response(req_id).await?;  // <--- waits here until forever
println!("Received response: {:?}", res);

```

with my structs

```

use ros2_client::Message;
use serde::{Deserialize, Serialize};

pub struct RosService;
impl Service for RosService {
    type Request = example_interfaces::AddTwoIntsReq;
    type Response = example_interfaces::AddTwoIntsRes;

    fn request_type_name(&self) -> &str { "AddTwoIntsReq" }
    fn response_type_name(&self) -> &str { "AddTwoIntsRes" }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AddTwoIntsReq {
    pub a: i64,
    pub b: i64,
}

impl Default for AddTwoIntsReq {
    fn default() -> Self {
        AddTwoIntsReq {
            a: 0,
            b: 0,
        }
    }
}

impl Message for AddTwoIntsReq {}

```

**Comment by jhelovuo** [comment]
Hello Nisse,

Interoperability between Rust  `ros2-client` and ROS 2 libraries (`rclcpp` and `rclpy`) should work out of the box. We have not yet extensively tested against Jazzy, so some incompatibilities may have popped up.  FastDDS from eProsima has worked quite nicely for a long time already, so that should work also.

I understand from your message that you have tried to establish a working baseline configuration by running ROS 2's example `demo_nodes_cpp` or `demo_nodes_py` pacakges against `ros2-client`'s built-in examples, such as `async_service_client` and `async_service_server`. This is a good approach.

Now, I just tried to reproduce the problems you describe. I am running Ubuntu 24 LTS on virtual x86_64, with ROS 2 Jazzy installed using `apt` and default settings. `ros2-client` is the latest `master` commit from GitHub.

### Scenario 1: `cargo run --example=async_service_client` connecting to `ros2 run demo_nodes_cpp add_two_ints_server`

This seems to run just fine. Discovery takes a few seconds, but the client and server connect and communicate. The start-up order of client and server does not matter. Client or server can be stopped and another one started, and communication resumes as expected. I cannot reproduce any problem here.

### Scenario 2: `ros2 run demo_nodes_cpp add_two_ints_client` connecting to `cargo run --example=async_service_server`

Does not work.  Symptoms seems similar to what you describe. There is a Discovery phase, about 3 seconds, during which the client reports `service not available, waiting again...`. Then client goes silent. Server reports `request: 2 + 3`, and after that nothing.

Inspecting network traffic on DDS/RTPS level reveals the following:

* Lots of Discovery traffic, as usual. Readers/Writers for Topics  `rr/add_two_intsReply` and `rq/add_two_intsRequest` are being announced, as expected.
* FastDDS publishes request `2+3`, as SequenceNumber 1, i.e. first message it has written to the request topic.
* RustDDS publishes reply `5` as SequenceNumber 1 also, on the reply topic. Request --> Response delay is < 1ms.
* FastDDS acknowledges receiving SequenceNumber 1 on the reply topic.

So it seems that RTPS level is working as expected, but the protocol stack at the client end running `rclcpp` does not like the reply, and it is not delivered to the demo client application. The cause is still unclear to me. This needs further investigation.

Can you try the same scenarios and report how they work for you?

**Comment by jhelovuo** [comment]
It turns out that FastDDS behaviour had changed. Thank you for bringing this to our attention.

Service messaging (actually RPC over DDS) requires something called RELATED_SAMPLE_IDENTITY to correlate Response to the correct Request. In `ServiceMapping::Enhanced` this is transferred as a part of DATA submessage in an element called Inline QoS, which is a list of RTPS Parameters. FastDDS used to identify, incorrectly, the Parameter RELATED_SAMPLE_IDENTITY as number 0x800f. RustDDS was written to be compatible with this to allow interoperability.

Now FastDDS has changed the identifier to the correct value 0x0083, which did not work with RustDDS, as FastDDS (or its RMW implementation) did not accept the old identifier anymore.

Additionally, eProsima has decided that RELATED_SAMPLE_IDENTITY no longer refers to the GUID of Writer sending the Service Request, but, apparently, the Reader that is supposed to receive the Reply, or something else. And it no longer contains the SequenceNumber of the Request, but `SEQUENCE_NUMBER_UNKNOWN`. However, the Service Response is supposed to contain the SequenceNumber of the DATA submessage carrying the Request, or it will not be accepted. I did not fully understand the logic behind this.

I added compatibility logic to RustDDS and `ros2-client` and released version 0.7.6. This works for me for both Scenarios 1 & 2 in the previous comment.

**Comment by nisseknudsen** [comment]
Hey @jhelovuo , 

thank you for your awesome answer and the fix release! I can confirm that my ros2 client -> rust (`ros2-client`) service  works now as expected 🙏 

I do still have an issues with rust client -> ros2 service. I noted that despite running both client and server on the same local host, I receive sometimes 0, sometimes more messages out of a 5 message loop (on average 2 out of 5). I tried a `Reliable` QoSPolicy, too (from this [issue comment](https://github.com/jhelovuo/ros2-client/issues/25#issuecomment-2039341450) ), but even then same result. Is this an issue with `ros2-client` or am I barking up the wrong tree (i.e., is it instead ROS2 / DDS)?

This is what I'm running:

```
let proxy_ros_client = Arc::new(node.create_client::<example_interfaces::srv::AddTwoInts>(
        ServiceMapping::Enhanced,
        &Name::new("/", &ros_service_name)?,
        &ServiceTypeName::new("example_interfaces", "AddTwoInts"),
        QosPolicies::default(),
        QosPolicies::default(),
    )?);

    println!("{:?}", &ros_service_name);

    let ros_request = example_interfaces::srv::AddTwoIntsReq {
        a: 40 as i64,
        b: 2 as i64,
    };

    for i in 0..5 {
        match proxy_ros_client.send_request(ros_request.clone()) {
            Ok(id) => {
                println!(">>> request sent a=40 b=2, {:?}", id);
            }
            Err(e) => {
                println!(">>> request sending error {:?}", e);
            }
        }
        // sleep for 1 second
        std::thread::sleep(std::time::Duration::from_secs(1));
    }
```

when running `examples/async_service_client` or `examples/ros2_service_client`, I do also see dropped messages. I'm wondering what's the safest policy that kind of guarantees communication for client/services.

**Comment by jhelovuo** [comment]
Hi @nisseknudsen ,

Please check that you are running a `.spinner()` in your ROS 2 nodes, as shown in https://github.com/jhelovuo/ros2-client/blob/master/examples/async_service_client/main.rs#L71 . Without that there is no background processing running at ROS 2 level, and Services may not work.

Additionally, Service Clients should `.wait_for_service()` , as shown in https://github.com/jhelovuo/ros2-client/blob/master/examples/async_service_client/main.rs#L89 . Otherwise, there may be no-one responding. Even though a Server was started before a Client, they have not discovered each other immediately when a Client starts up.

If you still have lost requests or responses after trying these, then please make a minimal but complete example program to reproduce the problem.

**Comment by nisseknudsen** [comment]
Ah awesome, that really helps to understand! I'll make sure to extend my code with the spinner and the waiting.
